#!/bin/bash

TESTS="*.demo"

for prog in $TESTS
do
    echo "Testing $prog"
    java -jar rewritedemo.jar $prog
    status=$?
    echo "exit code $status"
    if [[ $status != 0 ]]
    then
        exit $status
    fi
    echo ""
done
